### ISSUE TITLE
Would it be possible to apply it for a certain user or certain authorization?

### ISSUE THREAD

**Issue by Chardonneaur** [openmost/CodeInjector#1]
Hi,

Would it be possible to apply it for a certain user or certain authorization?
The typical use case would be the following one, having one stylesheet applied to hide most of Matomo reports to users having a read only permission. As a result, they don't see those features but super user, admin etc can still view them.

**Comment by ronan-hello** [comment]
Yes, maybe for Administors access ?

**Comment by ronan-hello** [comment]
After all, this could be another plugin such as “Hide some reports for users with role XXX”
This could be a greate idea!
